services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    ports:
      - '2025:3000'
    restart: unless-stopped
    volumes:
      - ./data/auth:/app/auth
      - ./data/cache:/app/cache
      - ./data/db:/app/data/persistance
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/persistance/
      - DB_FILENAME=botConfigs.db
      - AUTH_PATH=/app/auth
      - CACHE_PATH=/app/cache
    user: "1000:1000"
    networks:
      - bot-net

networks:
  bot-net:
    external: true