services:
    whatsapp-bot:
        build: .
        container_name: whatsapp-bot
        ports:
            - '2025:3000'
        restart: unless-stopped
        volumes:
            - ./session:/app/session
        networks:
            - bot-net

networks:
    bot-net:
        external: true
